name: "\U0001F41E Bug"
description: Hiba kezelési jegy
labels: ["bug"]
body:
  - type: textarea
    id: specication
    attributes:
      label: Specifikáció
      description: Mi a hiba?
    validations:
      required: true
  - type: textarea
    id: expected_behavior
    attributes:
      label: Elvárt működés
      description: Hogyan lenne jó?
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Előidézés
      description: Hogyan tudom előidézni? Milyen ismert feltételei vannak?
    validations:
      required: false
  - type: input
    id: link
    attributes:
      label: Link
      description: Asana, Sentry, Slack url
    validations:
      required: false  
