name: "🚀 Feature"
description: Új feature
labels: ["feature"]
body:
  - type: textarea
    id: specication
    attributes:
      label: Specifikáció
      description: Technikai feladatok listája. Új tábla, CRUD endpoint új cron, service stb… ami X,Y feladatot kell, hogy ellásson.
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Kontextus
      description: Rövid bevezetés az előzményről, mi az alapállapot. Nem kötelező, de jövőben segíti a hiba keresést ha több információ van a feladat hátteréről.
    validations:
      required: false
  - type: textarea
    id: preconditions
    attributes:
      label: Előfeltételek
      description: Bármilyen lépés aminek teljesülnie kell mielőtt el lehet kezdeni a megvalósítást.
    validations:
      required: false
  - type: textarea
    id: business_values
    attributes:
      label: Üzleti elvárások
      description: Mi az az üzleti érték aminek meg kell valósulnia ahhoz, hogy a taskot késznek lehessen minősíteni. Kijelentések amik alapján tesztelhető a fejlesztés.
    validations:
      required: false
  
